# Generated by Django 4.0.5 on 2022-06-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='writer',
        ),
    ]
